name: CI

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Create .env.local file
        run: |
          echo "NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN=${{ secrets.NEXT_PUBLIC_SHOPIFY_STORE_DOMAIN }}" >> .env.local
          echo "NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_SHOPIFY_STOREFRONT_ACCESS_TOKEN }}" >> .env.local
          echo "GELATO_API_KEY=${{ secrets.GELATO_API_KEY }}" >> .env.local
          echo "PRINTIFY_API_TOKEN=${{ secrets.PRINTIFY_API_TOKEN }}" >> .env.local
          echo "PIRATE_SHIP_API_KEY=${{ secrets.PIRATE_SHIP_API_KEY }}" >> .env.local
          echo "PRINTIFY_WEBHOOK_SECRET=${{ secrets.PRINTIFY_WEBHOOK_SECRET }}" >> .env.local
          echo "GELATO_WEBHOOK_SECRET=${{ secrets.GELATO_WEBHOOK_SECRET }}" >> .env.local
          echo "NEXT_PUBLIC_URL=http://localhost:3000" >> .env.local

      - name: Run linting
        run: pnpm lint

      - name: Run unit tests
        run: pnpm test

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Run E2E tests
        run: pnpm test:e2e
